apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: selfcrds.clustar.ai
spec:
  group: clustar.ai
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: selfcrds
    singular: selfcrd
    kind: SelfCRD
    shortNames:
    - selfcrd
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            username:
              type: string
            custom_id:
              type: string
